### ISSUE TITLE
Document "Statistical Aspect"

### ISSUE THREAD

**Issue by scw** [EsriOceans/btm#70]
from @patiam --

Help and perhaps parameter entry descriptions for Statistical Aspect
   need to explain the cos(Aspect) = "northness" and sin(Aspect) = "eastness".
   A citation would be good too, like Roberts, D. W. 1986. Ordination on
   the basis of fuzzy set theory. Vegetatio 66:123-31.

**Comment by scw** [comment]
Implemented by @noahslocum with 72f4f7d8ac239af6211d376a02b045c9c59345d3.

**Comment by deepseadawn** [comment]
Good!
